suspect/processing/denoising.py, tests/test_mrs/test_processing.py
Changed the sliding_window and svd methods in suspect.processing.denoising to retain the data type of the input signal when denoising.
 Added tests in tests.test_mrs.test_processing to ensure that the denoising methods retain the input signal data type. ComplexWarning is raised as an error if not.
=> Closes #23

requirements.txt, suspect/fitting/singlet.py
Modified the fit function in singlet.py to use the adjust_phase() function from the suspect API instead of implementing its own function. Deleted the phase_fid() function because it's redundant now. Closes #31
Fixed some formatting in singlet.py that was causing PEP8 warnings
Modified the project requirements to include numpy and lmfit
=> Use common phase adjust function when fitting #31

suspect/processing/frequency_correction.py
BUG: Spectral registration initial guess is negated
Closes #33 by reversing the returned value of spectral registration to be the amount shifted, rather than the amount to correct.
=> BUG: Spectral registration initial guess is negated

.travis.yml, suspect/processing/denoising.py, tests/test_mrs/test_processing/test_denoising.py
BUG: Closes #39 - fixed float indices in denoising functions
This PR closes issue #39 by making sure that all variables used for
slice indices in the spline denoising function are correctly integer
typed. The same was also done for the wavelet denoising function.
Two tests were added to check for this error in future.
=> BUG: Closes #39 - fixed float indices in denoising functions

suspect/io/twix.py
twix files have a header encoded in the latin-1 encoding, previous
versions of suspect used an incorrect windows-1252 in the
anonymize_twix() function.
=> Fixes #52 by changing the encoding for twix headers

suspect/_transforms.py, suspect/base.py, tests/test_mrs/test_base.py
The `ImageBase.from_scanner()`/`to_scanner()` functions now accept
`numpy.ndarray`s of coordinates as well as simple x, y, z arguments.
Fixes #63
=> ENH: ImageBase transforms can apply to arrays of coords

suspect/image/__init__.py, suspect/image/_mask.py, tests/test_mrs/test_image.py
Added new create_mask() function to image submodule, which creates a
volumetric mask of a spectroscopy voxel on a reference image volume.
Partially fixes #62. For now this only works with single voxel data,
until #50 is fixed to allow reliable information about the number of
voxels.
=> ENH: create_mask() function for voxel on reference image

suspect/base.py, suspect/image/_mask.py
The image.create_mask() function now returns an ImageBase rather than
a bare ndarray, so that it can be more easily saved with the transform
etc. In addition, the ImageBase class is modified to always copy the
transform during initialisation, to avoid accidentally overwriting the
transforms for parents during any modification.
=> BUG: image.create_mask now returns ImageBase

setup.py, suspect/image/_image.py, tests/test_mrs/test_image.py
Added functions to read and write ImageBase objects to the nifti file
format. Uses nibabel to handle actual disk operations. Note that the
coordinate system used by suspect is the DICOM system, Nifti files
are converted at save/load to this system.
=> ENH: save and load to Nifti files

suspect/base.py, tests/test_mrs/test_base.py
It is now possible to access the various normalised axes from ImageBase,
including both row/col/slice axes and closest to axial/coronal/sagittal.
=> ENH: Add axis properties to ImageBase

suspect/base.py, tests/test_mrs/test_base.py, tests/test_mrs/test_image.py
Previously sample had some issues where using a single slice for the
output shape would cause the slice dimension to be dropped when
transforming the coordinates which would interfere with doing the
interpolation. This is fixed by coercing the transformed coordinates
back into the target output shape.
In addition this brought to light another bug where the row_vector() and
col_vector() functions where swapped, which led to some transposement
problems.
Fixes #90
Fixes #92
=> BUG: Fixes for resample()

suspect/io/philips.py
The value for dt in the Philips SDAT reading code was hardcoded.
This change fixes it to be read out of the file instead. There
seem to be multiple ways of accessing the dt parameter, none of
them that are simply called dt. Currently the value is computed
from the column extrema (start and end times of the FID) divided
by the number of columns.
=> BUG: Fixed dt parameter from SDAT

docs/changelog.rst, suspect/io/twix.py
load_twix now checks to see if the frame of reference is anonymised
before trying to extract information from it
=> BUG: load_twix fails on anonymised frame of reference

suspect/io/tarquin.py
This commit modifies the tarquin processing to allow the passing
of a wref MRSData object.
Closes #109
=> ENH: Support wref in tarquin processing

suspect/io/tarquin.py, tests/test_mrs/test_io/test_tarquin.py
When processing data with TARQUIN, if the return code is not 0,
stderr from TARQUIN is raised as an exception to the user.
Closes #111
=> #BUG: TARQUIN errors are reported to user

docs/changelog.rst, suspect/image/_image.py
This commit changes the way DICOM files are loaded into a
volume, instead of looking for .ima or .dcm files, the
extension from the supplied slice is used to identify
other potential slices.
=> BUG: Loading DICOM files with non-Siemens extensions

docs/changelog.rst, suspect/processing/channel_combination.py
The functions to calculate channel combination weights,
`combine_channels()` and `svd_weighting()` previously required the
channels to be in the first axis of the data passed in to them. Now
we can instead pass an axis parameter into the function to specify
which axis contains the channels dimension. The default value of this
parameter is now -2, which is the default for Suspect loaded MRSData
objects.
Fixes #128
=> ENH: Adding axis to channel combination functions

docs/changelog.rst, suspect/image/_image.py, suspect/io/ge.py, suspect/io/philips.py, suspect/io/rda.py, suspect/io/siemens.py, suspect/io/twix.py, suspect/mrsobjects.py, tests/test_mrs/test_ima.py, tests/test_mrs/test_rda.py, tests/test_mrs/test_twix.py
This commit adds the TR property to MRSBase objects, read from the
various data formats supported. This is primarily intended to be
useful in calculating attenuation of water signals for absolute
quantification calculation.
Closes #135
=> ENH: Add TR to MRSBase objects

docs/changelog.rst, docs/fitting_api.rst, docs/index.rst, suspect/fitting/__init__.py, suspect/fitting/_quant.py, suspect/fitting/tarquin.py
This commit adds functions associated with calculating scaling factors
for absolute quantification. It also modifies the Tarquin `process()`
function to accept this scaling factor as a parameter, and moves that
function from the `io` module to the `fitting` module.
Closes #137
=> ENH: Add absolute quantification functionality

docs/changelog.rst, suspect/base.py, tests/test_mrs/test_base.py
The `_closest_axis()` function was not normalising the voxel direction
vectors so for an oblong and oblique voxel the dot product with a
reference vector (like (0, 1, 0)) could be larger for the long axis
than the more parallel one.
=> #BUG error selecting scanner axes in oblong voxels

docs/changelog.rst, suspect/io/twix.py
This commit adds code to anonymize Siemens TWIX files of VD and VE
version.
Fixes #11
=> #ENH Anonymization for TWIX VD/VE files

docs/changelog.rst, suspect/io/siemens.py
This fix is to address the problem that for some Siemens .IMA files the
calculated data shape does not match the size of the accompanying data,
resulting in an Exception. The change means that in this situation the
data shape is adjusted to use the data size, rather than the (multi-
dimensional) shape calculated from the header info.
fixes #143
=> #BUG143 incorrect data shape in some Siemens .IMA files

suspect/io/twix.py, tests/test_mrs/test_twix.py
Extract metadata from ASCONV header where possible as it's known to be much more stable across Siemens scanners. This version enables reading TWIX from VIDA scanner, which was previously not supported.
Also added known non-ASCONV regex.
Closes #149
=> Improve Siemens TWIX reader

suspect/io/twix.py
I found that in one of our VIDA scan, `VoiNormal` and `VoiInPlaneRot` only exist in the added regex, which essentially one of the existing regex without `<Precision>` information. 
In my case, the `VoiNormalSag`, `VoiNormalCor`, and `VoiInPlaneRot` are empty, while the `VoiNormalTra` is 1 and existed in other places (e.g. `sSpecPara.sVoI.sNormal.dTra`) with the same value.
Without adding this, it will raise `KeyError` since the patterns are not found.
https://github.com/openmrslab/suspect/blob/b35dbe684fd8edea4e9700dd3b8992401521d689/suspect/io/twix.py#L123
=> Added regex for extracting metadata on VIDA data

suspect/io/lcmodel.py
Added kwargs with defaults set to previously hard-coded values to maintain current behavior, but extend usability for other users.
=> Add kwargs to lcmodel RAW file generation methods

.github/workflows/ci-workflows.yaml, .github/workflows/publish-pypi.yaml
With its current version, Travis CI is not free anymore, so right now our CI could not run.
This PR will migrate suspect's CI to GitHub actions, which includes:
* `ci-workflows.yaml` to run tests
* `publish-pypi.yaml` to publish to main PyPI. This is mainly following [Python Packaging User Guide](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/).
=> Migrate ci

suspect/image/_image.py, suspect/io/dicom.py, suspect/io/siemens.py
`pydicom.dicomio.read_file` and `pydicom.read_file` are removed in pydicom v3.0.0 and it is suggested to use `pydicom.dcmread` instead. 
See release notes: https://pydicom.github.io/pydicom/stable/release_notes/index.html#version-3-0-0
=> read_file -> pydicom.dcmread

.github/workflows/ci-workflows.yaml, suspect/io/siemens.py
Rather than setting a starting point and incrementing by 1 to find CSA header and CSA data, user `dataset.group_dataset(group_number).iterall()`. 
The old method would fail if DICOM anonymisation stripped off the first expected element number, e.g. tag (0029,0010).
=> More general way to loop over dicom group

suspect/io/dicom.py, suspect/io/twix.py, tests/test_mrs/test_twix.py
To mitigate the slow reading for network drive access as reported in #182, `load_twix()` now supports handling binary stream. By doing this, user can increase the buffer size in the `open()` function. For example:
```python
In [4]: with open("/Users/darren/tmp/test-copy.dat", 'rb', buffering=1024*1024) as f:
...:     test_twix = suspect.io.load_twix(f)
...:
```
Per my testing, increasing the buffer size significantly improves the read speed. Using the same example in the issue, the total time is down to ~64s when increasing the buffer to 1MiB(vs ~1174s when using `io.DEFAULT_BUFFER_SIZE` , which is 8KiB in my environment).
```
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
14985   64.459    0.004   64.459    0.004 {method 'read' of '_io.BufferedReader' objects} # …
```
=> `suspect.io.load_twix()` to accept binary stream input
